export default {
  ActionTypes: {
    ADDING_MESSAGE: 'ADDING_MESSAGE',
    RECEIVE_MESSAGES: 'RECEIVE_MESSAGES',
    RECEIVE_CREATED_MESSAGE: 'RECEIVE_CREATED_MESSAGE',
    ERROR_MESSAGE: 'ERROR_MESSAGE',
    LOGIN_USER: 'LOGIN_USER',
    CREATE_USER: 'CREATE_USER',
    USER_ERROR: 'USER_ERROR'
  }
}